/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import AppSystem.Library;
import AppSystem.UserAccount;
import AppSystem.UserAccountDirectory;
import javax.swing.JOptionPane;

/**
 *
 * @author Ma2017
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Library library;
    private UserAccountDirectory useraccountDirectory;

    public MainJFrame() {
        initComponents();
        this.library = Library.getLibraryInstance();
        this.useraccountDirectory = library.getUseraccountDirectory();
        populateDropdown();
        this.setVisible(true);
    }

    public MainJFrame(Library li, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.library = Library.getLibraryInstance();
        this.useraccountDirectory = library.getUseraccountDirectory();
        populateDropdown();
    }

    public void populateDropdown() {
        roleBox1.removeAllItems();;
        for (String role : this.library.getUseraccountDirectory().getAllRoles()) {
            roleBox1.addItem(role);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        fieldusername1 = new javax.swing.JTextField();
        fieldpassword = new javax.swing.JTextField();
        roleBox1 = new javax.swing.JComboBox<>();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("WELCOME TO LIBRARY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 270, 40));
        getContentPane().add(fieldusername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 168, 42));
        getContentPane().add(fieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 168, 42));

        roleBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "System admin", "Customer", "Librarian" }));
        roleBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(roleBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 120, 30));

        loginBtn.setText("LOGIN");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void roleBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roleBox1ActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        String username = fieldusername1.getText();
        String password = fieldpassword.getText();
        String role = (String) roleBox1.getSelectedItem();

        if (this.useraccountDirectory.accountExists(username, password, role)) {

            UserAccount user = this.useraccountDirectory.getUserAccount(username, password, role);
            this.setVisible(false);
            user.getWorkArea(role, library, user);
        } else {
            JOptionPane.showMessageDialog(null, "Invalid credentials");
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldpassword;
    private javax.swing.JTextField fieldusername1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JComboBox<String> roleBox1;
    // End of variables declaration//GEN-END:variables
}
