/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.LibrarianWorkArea;

/**
 *
 * @author Ma2017
 */
public class AddBookJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddBookJPanel
     */
    public AddBookJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        AddBookBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        priceField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        priceField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        priceField2 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Book Gegre");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 79, -1));

        jLabel2.setText("Book Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 79, 20));

        jLabel3.setText("Book Author");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 79, -1));
        add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 160, -1));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 160, -1));

        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 160, -1));

        AddBookBtn.setText("Add");
        add(AddBookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 160, -1));

        jLabel4.setText("price");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 79, 20));
        add(priceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 160, -1));

        jLabel5.setText("ID");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 79, 20));
        add(IDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 160, -1));

        jLabel6.setText("Stauts");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 79, 20));
        add(priceField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 160, -1));

        jLabel7.setText("Duration field");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 79, 20));
        add(priceField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 160, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBookBtn;
    private javax.swing.JTextField IDField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField priceField;
    private javax.swing.JTextField priceField1;
    private javax.swing.JTextField priceField2;
    // End of variables declaration//GEN-END:variables
}
