/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.Medicine;
import Model.Observation;
import java.util.ArrayList;

/**
 *
 * @author Ma2017
 */
public class MedicineAssignJPanel extends javax.swing.JPanel {
    private Application application;
    /**
     * Creates new form MedicineAssignJPanel
     */
    public MedicineAssignJPanel() {
        initComponents();
    }
    
    MedicineAssignJPanel(Application application){
        initComponents();
        this.application = application;
        populateDropdowns();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ObservationBox = new javax.swing.JComboBox();
        medicineBox = new javax.swing.JComboBox();
        assign = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ObservationBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ObservationBoxItemStateChanged(evt);
            }
        });
        add(ObservationBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 157, 200, -1));

        medicineBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                medicineBoxItemStateChanged(evt);
            }
        });
        add(medicineBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, -1));

        assign.setText("Assign");
        assign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignActionPerformed(evt);
            }
        });
        add(assign, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 410, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 180, 30));

        jLabel2.setText("assignment of observation:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        jLabel3.setText("Observation:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, -1));

        jLabel4.setText("Medicine:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignActionPerformed
        Observation o = (Observation)ObservationBox.getSelectedItem();
        Medicine m = (Medicine)medicineBox.getSelectedItem();
        o.setMedication(m);
        
        
    }//GEN-LAST:event_assignActionPerformed

    private void medicineBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_medicineBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_medicineBoxItemStateChanged

    private void ObservationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ObservationBoxItemStateChanged
        Observation o = (Observation) ObservationBox.getSelectedItem();
        
        if(o.getMedication()!= null){
            jLabel1.setText(o.getMedication().getMedicineName());
        }
    }//GEN-LAST:event_ObservationBoxItemStateChanged
    
    public void populateDropdowns(){
        ArrayList<Medicine> medicines = this.application.getCatalog().getMedicineList();
        ArrayList<Observation> observations = this.application.getHistory().getVitalSignHistory();
        
        for(Observation o : observations){
            ObservationBox.addItem(o);
        }
        
        for(Medicine med : medicines){
            medicineBox.addItem(med);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ObservationBox;
    private javax.swing.JButton assign;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox medicineBox;
    // End of variables declaration//GEN-END:variables
}
