/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import Business.UserAccountDirectory;
import Customer.Customer;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ma2017
 */
public class CustomerManagementJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private Business business;
    DefaultTableModel tableModel;
    /**
     * Creates new form CustomerManagementJPanel
     */
    public CustomerManagementJPanel() {
        initComponents();
        
    }
    //上面的待删
    
    public CustomerManagementJPanel(Business business,UserAccount useraccount){
        initComponents();
        this.business=business;
        this.useraccount=useraccount;
        this.tableModel=(DefaultTableModel)jTable1.getModel();
        populate();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldage1 = new javax.swing.JTextField();
        fieldUsername1 = new javax.swing.JTextField();
        fieldname1 = new javax.swing.JTextField();
        fieldpassword1 = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fieldage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 120, -1));
        add(fieldUsername1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 120, -1));

        fieldname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldname1ActionPerformed(evt);
            }
        });
        add(fieldname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, -1));
        add(fieldpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 120, -1));

        addBtn.setText("add customer");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "User Name", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 400, 320));

        jLabel1.setText("age");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 50, -1));

        jLabel2.setText("name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel3.setText("UserName");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        jLabel4.setText("password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        UserAccountDirectory ua = this.business.getUseraccountDirectory();
        if(ua.accountExists(fieldUsername1.getText(),fieldpassword1.getText(),"customer")){
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken");
        }
        else{
//            System.out.println(fieldUsername1.getText());
            UserAccount user = this.business.getUseraccountDirectory().createUserAccount(fieldUsername1.getText(),fieldpassword1.getText(),"customer");
            this.business.getCustomerDirectory().createCustomer(user.getAccountId(),fieldname1.getText(),fieldage1.getText());
            populate();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void fieldname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldname1ActionPerformed

    public void populate(){
            tableModel.setRowCount(0);
            for(Customer c: this.business.getCustomerDirectory().getCustomerlist()){
                UserAccount u = this.business.getUseraccountDirectory().findById(c.getPersonID());
                
                Object[] row = new Object[4];
                row[0] = c.getPersonID();
                row[1] = c.getName();
                row[2] = u.getUsername();
                row[3] = u.getPassword();
                
                tableModel.addRow(row);
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField fieldUsername1;
    private javax.swing.JTextField fieldage1;
    private javax.swing.JTextField fieldname1;
    private javax.swing.JTextField fieldpassword1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
