/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import Business.UserAccountDirectory;
import Restaurant.DeliveryAgent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ma2017
 */
public class DeliveryAgentManagementJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private Business business;
    DefaultTableModel tableModel;
    /**
     * Creates new form DeliveryAgentJPanel
     */
   

    public DeliveryAgentManagementJPanel(Business business, UserAccount useraccount){
        initComponents();
        this.business=business;
        this.useraccount=useraccount;
        this.tableModel=(DefaultTableModel)jTable1.getModel();
        populate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldUsername = new javax.swing.JTextField();
        fieldname = new javax.swing.JTextField();
        fieldpassword = new javax.swing.JTextField();
        fieldage = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fieldUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 120, -1));
        add(fieldname, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 120, -1));
        add(fieldpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 120, -1));
        add(fieldage, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 120, -1));

        addBtn.setText("add Agent");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 344, 109, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "User Name", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 83, 400, 320));

        jLabel2.setText("name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel3.setText("UserName");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel4.setText("password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jLabel1.setText("age");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 50, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        UserAccountDirectory ua = this.business.getUseraccountDirectory();
        if(ua.accountExists(fieldUsername.getText(),fieldpassword.getText(),"agent")){
            JOptionPane.showMessageDialog(null, "Sorry credentials are taken");
        }
        else{
            UserAccount user = this.business.getUseraccountDirectory().createUserAccount(fieldUsername.getText(),fieldpassword.getText(),"agent");
            this.business.getDeliverAgentDirectory().createAgent(user.getAccountId(),fieldname.getText(),fieldage.getText());
            populate();
        }
    }//GEN-LAST:event_addBtnActionPerformed

    public void populate(){
            tableModel.setRowCount(0);
            for(DeliveryAgent d: this.business.getDeliverAgentDirectory().getAgentList()){
                UserAccount u = this.business.getUseraccountDirectory().findById(d.getPersonID());
                
                Object[] row = new Object[4];
                row[0] = d.getPersonID();
                row[1] = d.getName();
                row[2] = u.getUsername();
                row[3] = u.getPassword();
                
                tableModel.addRow(row);
            }
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField fieldUsername;
    private javax.swing.JTextField fieldage;
    private javax.swing.JTextField fieldname;
    private javax.swing.JTextField fieldpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
