/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.ManagerWorkArea;

import Business.Business;
import Business.UserAccount;
import Restaurant.DeliveryAgent;
import Services.Order;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ma2017
 */
public class OrderManagementJPanel extends javax.swing.JPanel {
    private UserAccount useraccount;
    private Business business;
    DefaultTableModel tableModel;
    /**
     * Creates new form OrderManagementJPanel
     */
    public OrderManagementJPanel() {
        initComponents();
    }
    
    OrderManagementJPanel(Business business, UserAccount useraccount){
        initComponents();
        this.business=business;
        this.useraccount=useraccount;
        this.tableModel=(DefaultTableModel)jTable1.getModel();
        populateDp();
        populate();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBox1 = new javax.swing.JComboBox<>();
        assignBtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Order ID", "Customer", "Delivery Man"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 34, 377, 233));

        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 170, -1));

        assignBtn.setText("Assign");
        assignBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignBtnActionPerformed(evt);
            }
        });
        add(assignBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void assignBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBtnActionPerformed
        DeliveryAgent agent = (DeliveryAgent)jComboBox1.getSelectedItem();
        int selectedRow = jTable1.getSelectedRow();
        Order o = (Order) jTable1.getValueAt(selectedRow,0);
        o.setAgent(agent);
        agent.addDeliveryOrder(o);
        
        populate();
        
    }//GEN-LAST:event_assignBtnActionPerformed

    public void populate(){
        tableModel.setRowCount(0);
        for (Order o : this.business.getAllOrders().getOrderlist()){
            Object[] row = new Object[3];
            
            row[0]=o;
            row[1]=o.getCustomer().getPersonID();
            row[2]=o.getAgent().getPersonID();
            
            tableModel.addRow(row);
        }
    }
    
    public void populateDp(){
        jComboBox1.removeAllItems();
        for (DeliveryAgent d: this.business.getDeliverAgentDirectory().getAgentList() ){
            jComboBox1.addItem(String.valueOf(d));
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignBtn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
